version: 2
updates:
  # version updates: enabled
  # security updates: enabled
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # version updates: disabled
  # security updates: enabled
  # https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
